service: shared-layer
frameworkVersion: '3'

# Force redeploy for CORS updates - updated 2025-09-10

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

layers:
  sharedUtilsLayer:
    path: .
    name: shared-utils
    compatibleRuntimes: [nodejs18.x]

# Export the Layer ARN so other services can import it with ${cf:shared-layer-${sls:stage}.SharedUtilsLayerArn}
resources:
  Outputs:
    SharedUtilsLayerArn:
      Value:
        Ref: SharedUtilsLayerLambdaLayer
      Export:
        Name: shared-layer-arn-${sls:stage}
