service: thumbnails

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    CDN_DOMAIN: ${self:custom.cdnDomain}
    FILE_BUCKET: ${env:FILE_BUCKET, 'mylg-files-v12'}
    FILE_CDN: ${env:FILE_CDN, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::${self:custom.bucketName}/*
        - Effect: Allow
          Action:
            - s3:GetBucketLocation
          Resource: arn:aws:s3:::${self:custom.bucketName}

plugins:

custom:
  bucketName: mylg-files-v12
  bucketRegion: ${self:provider.region}
  cdnDomain: https://d3kix94vejprx7.cloudfront.net

functions:
  generateThumbnail:
    handler: index.handler
    layers:
      - ${cf:shared-layer-${sls:stage}.SharedUtilsLayerArn}
    events:
      - http:
          path: /thumbnails
          method: post
          cors:
            origins:
              - 'https://beta.mylg.studio'
              - 'https://mylg.studio'
              - 'http://localhost:3000'
              - 'http://localhost:5173'
              - 'http://192.168.1.172:5173'
              - 'http://192.168.1.200:5173'
              - 'http://192.168.1.172:3000'
              - 'http://192.168.1.200:3000'
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - X-CSRF-Token
              - x-csrf-token
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false
    timeout: 60
    memorySize: 2048

package:
  individually: true
  exclude:
    - .git/**
    - test/**
    - node_modules/sharp/**
